version: "3"
services:
  app:
    build: .
    container_name: app
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - SERVER_PORT
      - CRON_EXPRESSION
      - CRON_THREAD_PREFIX
      - CRON_POOL_SIZE
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}